[project]
name = "mqttsink"
version = "1.0.0"
description = "MQTT Sink"
authors = [{name = "Yann Belin", email = "yann.belin@pm.me"}]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
paho-mqtt = "^2.1.0"
requests = "^2.33.1"
pydantic = "^2.13.4"
psutil = "^7.2.2"

[tool.poetry.scripts]
mqttsink = 'mqttsink.run:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
